# Generated by Django 5.0.2 on 2024-03-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_remove_product_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
